import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import Button from '@/components/Button'
import { SideBar } from '@/components/SideBar'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ru">
      <body className={inter.className + " flex h-svh bg-slate-300 overflow-hidden"}>
        <SideBar />
        <main>{children}</main>
      </body>
    </html>
  )
}
