import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import Button from '@/components/Button'
import { SideBar } from '@/components/SideBar'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {

  const cookieStore = cookies()

  return (
    <html lang="ru">
      <body className={inter.className + " flex bg-sidebar-color"}>
        {
         // cookieStore.get("token") ? (<><SideBar /><main>{children}</main></>) : (<main>{children}</main>)
         <>
         <SideBar/>
         <main>{children}</main>
         </>
        }
      </body>
    </html>
  )
}
